/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/validations": {
    /** given account id and email or phone number, returns validation id and status */
    post: operations["post-validations"];
    parameters: {};
  };
  "/validations/{id}": {
    get: operations["get-validations-id"];
    parameters: {
      path: {
        id: string;
      };
    };
  };
}

export interface components {
  schemas: {};
}

export interface operations {
  /** given account id and email or phone number, returns validation id and status */
  "post-validations": {
    parameters: {};
    responses: {
      /** OK */
      201: {
        content: {
          "application/json": {
            status?: string;
            id?: string;
          };
        };
      };
      /** Unauthorized */
      401: unknown;
    };
    requestBody: {
      content: {
        "application/json": {
          accountId?: string;
          emails?: {
            value?: string;
          }[];
          phoneNumbers?: {
            value?: string;
          }[];
        };
      };
    };
  };
  "get-validations-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            status: string;
            id: string;
          };
        };
      };
      /** Unauthorized */
      401: unknown;
    };
  };
}
