/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/offers": {
    /** gets offers for a given user/location */
    post: operations["post-products"];
    parameters: {};
  };
  "/offers/{OfferId}": {
    get: operations["get-products-offers"];
    parameters: {
      path: {
        OfferId: string;
      };
    };
  };
}

export interface components {
  schemas: {};
}

export interface operations {
  /** gets offers for a given user/location */
  "post-products": {
    parameters: {};
    responses: {
      /** Offer Created */
      200: {
        content: {
          "application/json": {
            id: string;
            items: {
              plan?: {
                download_speed: number;
                upload_speed: number;
                price: {
                  value: number;
                  type: string;
                };
                data_limit?: number;
                name: string;
              };
            }[];
          };
        };
      };
      /** Missing Required Information */
      400: unknown;
      /** Not Found */
      404: unknown;
    };
    /** Post the necessary fields for the API to create a new user. */
    requestBody: {
      content: {
        "application/json": {
          location: {
            address?: {
              streetAddress?: string;
              locality?: string;
              region?: string;
              postalCode?: string;
              country?: string;
            };
            coordinates?: {
              latitude?: number;
              longitude?: number;
            };
          };
          partyId: string;
        };
      };
    };
  };
  "get-products-offers": {
    parameters: {
      path: {
        OfferId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            id: string;
            items: {
              plan?: {
                download_speed: number;
                upload_speed: number;
                price: {
                  value: number;
                  type: string;
                };
                data_limit: number;
                name: string;
              };
            }[];
          };
        };
      };
      /** Bad Request */
      400: unknown;
      /** Not Found */
      404: unknown;
    };
  };
}
